export const SOCKET_EVENTS = {
  USER_JOINED_ROOM: 'USER_JOINED_ROOM',
  USER_JOINED_LOBBY: 'USER_JOINED_LOBBY',
  USER_LEFT_ROOM: 'USER_LEFT_ROOM',
  USER_LEFT_LOBBY: 'USER_LEFT_LOBBY',

  // rooms gateway
  ROOM_CREATED: 'ROOM_CREATED',
  ROOM_DELETED: 'ROOM_DELETED',

  // events gateway
  USER_DISCONNECTED: 'USER_DISCONNECTED',
  USER_CONNECTED: 'USER_CONNECTED',

  // game gateway
  USER_READY: 'USER_READY',
  KICK_USER_FROM_ROOM: 'KICK_USER_FROM_ROOM',
  GAME_STARTED: 'GAME_STARTED',
  GAME_ENDED: 'GAME_ENDED',
  CORRECT_ANSWER_SELECTED: 'CORRECT_ANSWER_SELECTED',
  WRONG_ANSWER_SELECTED: 'WRONG_ANSWER_SELECTED',

  // messages gateway
  FRIEND_REQUEST_SENT: 'FRIEND_REQUEST_SENT',
  FRIEND_REQUEST_ACCEPTED: 'FRIEND_REQUEST_ACCEPTED',
  FRIEND_REMOVED: 'FRIEND_REMOVED',

  // leagues gateway
  // REQUEST_JOIN_LEAGUE: 'REQUEST_JOIN_LEAGUE',
  // APPROVE_JOIN_LEAGUE: 'APPROVE_JOIN_LEAGUE',
  USER_JOINED_LEAGUE_ROOM: 'USER_JOINED_LEAGUE_ROOM',
  USER_JOINED_LEAGUE: 'USER_JOINED_LEAGUE',
  USER_LEFT_LEAGUE_ROOM: 'USER_LEFT_LEAGUE_ROOM',
  USER_LEFT_LEAGUE: 'USER_LEFT_LEAGUE',
  // USER_REMOVED_FROM_LEAGUE: 'USER_REMOVED_FROM_LEAGUE',
  USER_READY_IN_LEAGUE: 'USER_READY_IN_LEAGUE',
  USER_NOT_READY_IN_LEAGUE: 'USER_NOT_READY_IN_LEAGUE',
  NEXT_QUIZ_SELECTED: 'NEXT_QUIZ_SELECTED',
  LEAGUE_GAME_STARTED: 'LEAGUE_GAME_STARTED',
  LEAGUE_GAME_ENDED: 'LEAGUE_GAME_ENDED',
};
