export const SOCKET_EVENTS = {
  USER_JOINED_ROOM: 'USER_JOINED_ROOM',
  USER_JOINED_LOBBY: 'USER_JOINED_LOBBY',
  USER_LEFT_ROOM: 'USER_LEFT_ROOM',
  USER_LEFT_LOBBY: 'USER_LEFT_LOBBY',
  ROOM_CREATED: 'ROOM_CREATED',
  ROOM_DELETED: 'ROOM_DELETED',
  USER_DISCONNECTED: 'USER_DISCONNECTED',
  GAME_STARTED: 'GAME_STARTED',
  CORRECT_ANSWER_SELECTED: 'CORRECT_ANSWER_SELECTED',
  WRONG_ANSWER_SELECTED: 'WRONG_ANSWER_SELECTED',
};
