export const SOCKET_EVENTS = {
  USER_JOINED_ROOM: 'USER_JOINED_ROOM',
  USER_JOINED_LOBBY: 'USER_JOINED_LOBBY',
  USER_LEFT_ROOM: 'USER_LEFT_ROOM',
  USER_LEFT_LOBBY: 'USER_LEFT_LOBBY',
  ROOM_CREATED: 'ROOM_CREATED',
  ROOM_DELETED: 'ROOM_DELETED'
};
